---

- name: AmpInstall
  hosts: linux

  tasks:
    - name: Check for package installation
      command: dpkg-query -W [remote filename]
      register: already_installed
      failed_when: already_installed.rc > 1
      changed_when: already_installed.rc == 1
    - name: Create Downloads folder
      file:
        path: ~/Downloads
        mode: 0755
        state: directory
    - name: Download Secure Endpoint Connector
      become: true
      copy:
        src: [local filename and location]
        dest: /home/[username]/Downloads/[remote filename].deb
      when: already_installed.rc == 1
    - name: Install my_package
      become: true
      command: dpkg -i /home/[username]/Downloads/ampInstaller.deb
